daftarrumahsakit/urls.py
from django.urls import path
from . import views

app_name = 'daftarrumahsakit'

urlpatterns = [
    path('', views.home, name='home'),
    path('<single_slug>', views.single_slug, name='single_slug'),
    path('search/', views.search, name='search'),
]

forum/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "forum"

urlpatterns = [
    path('', views.index, name="index"),
    path('posts/<str:ordering>', views.index, name="sortPost"),
    path('view/<int:id>', views.view, name="view"),
    path('post/', views.post, name="post"),
    path('reply/<int:id>', views.reply, name="reply")
]

learningplaceApp/urls.py
from django.contrib import admin
from django.urls import path

from .views import index

app_name = "learningplace"

urlpatterns = [
    path("", index, name="index")
]

main/urls.py
from django.contrib import admin
from django.urls import path

from .views import index, Subscribe, SaveSubscription, developer

app_name = "main"

urlpatterns = [
    path('', index, name="index"),
    path('subscribe/', Subscribe, name="subscribe"),
    path('subscribe/save/', SaveSubscription, name="save"),
    path('developer/', developer, name="developer")
]

newnormalinfo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('rumahsakit/', include('daftarrumahsakit.urls')),
    path('tempatbelajar/', include('learningplaceApp.urls')),
    path('forum/', include('forum.urls')),
    path('account/', include('account.urls'))
]

main/models.py
from django.db import models

class Subscriber(models.Model):
    nama_subscriber = models.CharField(max_length=50)
    email_subscriber = models.CharField(max_length=50)
    newsletter = models.BooleanField(default=False)

main/forms.py
from django import forms

class AddSubscriber(forms.Form):
    attr_nama = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Nama...'
    }

    attr_email = {
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Email...'
    }

    attr_newsletter = {
        'type': 'checkbox',
        'class': 'form-control',
        'style':'width:20px;height:20px;'
    }

    nama_subscriber = forms.CharField(label='Masukkan nama:', max_length=50, required=True, widget=forms.TextInput(attrs=attr_nama))
    email_subscriber = forms.CharField(label='Masukkan email:', max_length=50, required=True, widget=forms.TextInput(attrs=attr_email))
    newsletter = forms.BooleanField(label='', required=False, widget=forms.CheckboxInput(attrs=attr_newsletter))

main/views.py
from django.shortcuts import render
from .forms import AddSubscriber
from .models import Subscriber

from learningplaceApp.forms import contactUsForm
from learningplaceApp.models import contactUs

def developer(request):
    return render(request, "main/developer-page.html")


def index(request):
    form = contactUsForm(request.POST or None)
 
    if form.is_valid():
        form.save()
        form = contactUsForm()

    context = {
        'form': form
    }
    return render(request, "main/index.html", context)

def Subscribe(request):
    subscriber_count = Subscriber.objects.count()
    response = {'add_subscriber' : AddSubscriber, 'subscriber_count' : subscriber_count}
    return render (request, 'main/subscribe.html', response)

def SaveSubscription(request):
    response = {'save_status':''}
    if (request.method == 'POST'):
        form = AddSubscriber(request.POST)
        if (form.is_valid()):
            nama_subscriber = form.cleaned_data['nama_subscriber'] 
            email_subscriber = form.cleaned_data['email_subscriber'] 
            newsletter = form.cleaned_data['newsletter']
            
            new_subscriber = Subscriber(
                nama_subscriber = nama_subscriber,
                email_subscriber = email_subscriber,
                newsletter = newsletter
            )

            new_subscriber.save()

            response['save_status'] = 'Subscribe berhasil!'
        else:
            response['save_status'] = 'Subscribe gagal'
    else:
        response['save_status'] = 'Something went wrong'

    return render (request, 'main/save.html', response)

templates/main/developer-page.html
{% extends 'base.html' %}
{% load static %}


    {% block css %}
        <link rel="stylesheet" href="{% static 'style.css' %}" /> 
    {% endblock %}

    {% block content %}  

  <!-- percobaan terbaru -->
  <!-- Developer Page -->
  
  <br>
  <br>
  <section id="team">
    <div class="container">
        <div class="section-header">
          <br>
            <h3> Welcome to Developer Page </h3>
            <br>
        
            <marquee> Introduce our Incredible Team ! :D </marquee>
          <br> 
          <br>
          <br>
          <br>
          
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-6 wow fadeInUp" style="visibility: visible; animation-name: fadeInUp;">
                <div class="member"> <img src="https://i.postimg.cc/sxkFXxzZ/CN36.png"  class="img-fluid" alt="">
                    <div class="member-info">
                        <div class="member-info-content">
                            <h4>Mochammed Daffa El Ghifari</h4> <span>Main Page</span>
                         
                          
                            <div class="social"> 
                              
                              <a href ="mailto: mochammed.daffa91@ui.ac.id" target="_blank" class="btn-floating btn-lg btn-email" type="button" role="button"><i class="fas fa-envelope"></i></a>
                              <a href = "https://www.instagram.com/delghifari_" target="_blank" class="btn-floating btn-lg btn-ins" type="button" role="button"><i class="fab fa-instagram"></i></a>
        
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s" style="visibility: visible; animation-delay: 0.1s; animation-name: fadeInUp;">
                <div class="member"> <img src="https://i.postimg.cc/KzqVw2CM/TH05.png" class="img-fluid" alt="">
                    <div class="member-info">
                        <div class="member-info-content">
                            <h4>Alfina Megasiwi</h4> <span>Daftar Rumah Sakit Rujukan</span>
                                 
                            <div class="social"> 
                              
                              <a href="mailto:alfina.megasiwi@ui.ac.id " target="_blank" class="btn-floating btn-lg btn-email" type="button" role="button"><i class="fas fa-envelope"></i></a>
                              <a href="https://www.linkedin.com/in/alfina-megasiwi-06879714a/?originalSubdomain=id"  target="_blank"class="btn-floating btn-lg btn-li" type="button" role="button"><i class="fab fa-linkedin-in"></i></a>
                              <a href="https://www.instagram.com/alfnms" target="_blank" class="btn-floating btn-lg btn-ins" type="button" role="button"><i class="fab fa-instagram"></i></a>
        
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
                <div class="member"> <img src="https://i.postimg.cc/gjx5P7PB/profpic-uchi-copy-1.png" class="img-fluid" alt="">
                    <div class="member-info">
                        <div class="member-info-content">
                            <h4>Muchlisah Lusiambali</h4> <span> Learning Place Page <br>
                              (include: Contact Us Form) </span>

                              <div class="social"> 
                              
                                <a href="mailto: muchlisah.lusiambali@ui.ac.id" target="_blank" class="btn-floating btn-lg btn-email" type="button" role="button"><i class="fas fa-envelope"></i></a>
                                <a href="https://www.linkedin.com/in/uchiml/" target="_blank" class="btn-floating btn-lg btn-li" type="button" role="button"><i class="fab fa-linkedin-in"></i></a>
                                <a href="https://www.instagram.com/uchiml" target="_blank" class="btn-floating btn-lg btn-ins" type="button" role="button"><i class="fab fa-instagram"></i></a>
          
                              </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeInUp;">
                <div class="member"> <img src="https://i.postimg.cc/4yj041f4/FR52.png" class="img-fluid" alt="">
                    <div class="member-info">
                        <div class="member-info-content">
                            <h4>William</h4> <span>Forum</span>
                            
                            <div class="social"> 
                              
                              <a href="mailto: william92@ui.ac.id" target="_blank" class="btn-floating btn-lg btn-email" type="button" role="button"><i class="fas fa-envelope"></i></a>
                              <a href="https://www.linkedin.com/in/william-8611851a0/" target="_blank" class="btn-floating btn-lg btn-li" type="button" role="button"><i class="fab fa-linkedin-in"></i></a>
                              <a href="https://www.instagram.com/hori__75" target="_blank" class="btn-floating btn-lg btn-ins" type="button" role="button"><i class="fab fa-instagram"></i></a>
        
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



    {% endblock %}

templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Hello World!{% endblock %}
{% block head %}{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" /> 
{% endblock %}

{% block content %}
<div class="container-btn">
    <img src="https://files.catbox.moe/hzidkd.jpg" alt="test">
    <h1>NEW NORMAL INFO</h1>
    <a class="btn default-outline" href="{% url 'main:subscribe' %}">Subscribe</a>  
      
</div>

<div class="container" data-aos="fade-up">
    <div class="row">
        <div class="col-md-6 mt-5">
            <h1>Rumah Sakit</h1>
            <p>Anda dapat melihat daftar rumah sakit rujukan di sini</p>
            <a href="{% url 'daftarrumahsakit:home' %}" class="btn default-outline">RS</a>
        </div>
        <div class="col-md-6 mt-5">
            <h1>Learning Place</h1>
            <p>Anda dapat melihat daftar tempat belajar di sini</p>
            <a href="{% url 'learningplace:index' %}" class="btn default-outline">Learning Place</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 my-5">
            <h1>Forum</h1>
            <p>Anda dapat melihat topik diskusi dan berita terbaru mengenai new normal dan pandemi ini</p>
            <a href="{% url 'forum:index' %}" class="btn default-outline">Forum</a>
        </div>
        <div class="col-md-6 mt-5">
            <h1>Developer</h1>
            <p>Anda dapat melihat profile team New Normal Info</p>
            <a href="{% url 'main:developer' %}" class="btn default-outline">Developer</a>
        </div>
    </div>
    <br><br>
</div>
<br>
{% endblock %}

templates/main/save.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" /> 
{% endblock %}
{% block content %}
<div class='container-fluid p-5' style="margin: auto;">
    <div class='row mt-5'>
        <div class='col my-5' id="center-text">
            <h1>
                {{ save_status }}
            </h1>
        </div>
    </div>

    <div class='row justify-content-center'>
        <a class="btn btn-light btn-outline-secondary" href="{% url 'main:index' %}">Kembali</a>    
    </div>
</div>

{% endblock %}

templates/main/subscribe.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" /> 
{% endblock %}
{% block content %}
<div class="container-fluid p-5">
    <div class='breadcrumbs'>
        <div class='row'>
            <div class='col-lg-6'>
                <div class='container-btn'>
                    <img src="https://files.catbox.moe/j603xh.png" alt="Subscribe now!">
                </div>
            </div>
            <div class='col-lg-6 m-auto'>
                <h1>Bergabung sekarang</h1>
                <p>Ingin tetap up to date dengan informasi yang ada? Bergabunglah bersama {{ subscriber_count }} orang lainnya dan subscribe sekarang!</p>
            </div>
        </div>
        
    </div>

    <div class='row mt-5'>
        <div class='col my-3' id="center-text">
            <h1>Masukkan nama dan email</h1>
        </div>
    </div>

    <div class='row'>
        <div class='col'>
            <form action="save/" method="POST">
                <div class="form-group">
                    {% csrf_token %}

                    <div class='row'>
                        <div class='col-md-6 mb-5'>
                            {{ add_subscriber.nama_subscriber }}
                        </div>
                        <div class="col-md-6 mb-5">
                            {{ add_subscriber.email_subscriber }}
                        </div>
                    </div>

                    <div class="row">
                        <div class='col-md-6 mb-3 ml-auto'>
                            <div class='container pr-3 pl-0'>
                                {{ add_subscriber.newsletter }}
                                <p>Centang kotak ini untuk mendapatkan update terbaru di website kami pada email anda</p>
                            </div>
                        </div>
                        
                    </div>
                    
                </div>
                <button type="submit" class="btn btn-dark">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}