account/urls.py
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('signup/', views.signUp_view, name="signup"),
    path('logout/', views.logout_view, name="logout")
]

forum/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "forum"

urlpatterns = [
    path('', views.index, name="index"),
    path('posts/<str:ordering>', views.index, name="sortPost"),
    path('view/<int:id>', views.view, name="view"),
    path('post/', views.post, name="post"),
    path('reply/<int:id>', views.reply, name="reply")
]

main/urls.py
from django.contrib import admin
from django.urls import path

from .views import index, Subscribe, SaveSubscription, developer

app_name = "main"

urlpatterns = [
    path('', index, name="index"),
    path('subscribe/', Subscribe, name="subscribe"),
    path('subscribe/save/', SaveSubscription, name="save"),
    path('developer/', developer, name="developer")
]

newnormalinfo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('rumahsakit/', include('daftarrumahsakit.urls')),
    path('tempatbelajar/', include('learningplaceApp.urls')),
    path('forum/', include('forum.urls')),
    path('account/', include('account.urls'))
]

forum/models.py
from ckeditor.fields import RichTextField
from django import forms
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

class PostNode(models.Model):
    content = RichTextField(null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    post = models.ForeignKey('self', null=True, on_delete=models.CASCADE)
    time_creation = models.DateTimeField(auto_now_add=True)
    hidden = models.BooleanField(default=False)

    def get_topic(self):
        postnode = self
        while (postnode.post != None):
            postnode = postnode.post
        return postnode.topic

    def update_topic(self):
        topic = self.get_topic()
        topic.replyCountUp()
        return topic

    def has_replies(self):
        return self.postnode_set.first() is not None

    def get_creation_datetime(self):
        time = timezone.now()

        if (self.time_creation.year == time.year):
            if (self.time_creation.month == time.month):
                if (self.time_creation.day == time.day):
                    if (self.time_creation.hour == time.hour):
                        if (self.time_creation.minute == time.minute):
                            return str(time.second - self.time_creation.second) + " detik lalu"
                        else:
                            return str(time.minute - self.time_creation.minute) + " menit lalu"
                    else:
                        return str(time.hour - self.time_creation.hour) + " jam lalu"
                else:
                    return str(time.day - self.time_creation.day) + " hari lalu"
            else:
                return str(time.month - self.time_creation.month) + " bulan lalu"
        else:
            return self.time_creation

class Topic(models.Model):
    title = models.CharField(max_length=50)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    head = models.OneToOneField(PostNode, on_delete=models.CASCADE)
    recent_update = models.DateTimeField(auto_now=True)
    time_creation = models.DateTimeField(auto_now_add=True)
    reply_count = models.BigIntegerField(default=0)

    def replyCountUp(self):
        self.reply_count += 1
        self.save()

    def get_recent_datetime(self):
        time = timezone.now()

        if (self.recent_update.year == time.year):
            if (self.recent_update.month == time.month):
                if (self.recent_update.day == time.day):
                    if (self.recent_update.hour == time.hour):
                        if (self.recent_update.minute == time.minute):
                            return str(time.second - self.recent_update.second) + " detik lalu"
                        else:
                            return str(time.minute - self.recent_update.minute) + " menit lalu"
                    else:
                        return str(time.hour - self.recent_update.hour) + " jam lalu"
                else:
                    return str(time.day - self.recent_update.day) + " hari lalu"
            else:
                return str(time.month - self.recent_update.month) + " bulan lalu"
        else:
            return self.recent_update

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['title']

class PostNodeForm(forms.ModelForm):
    class Meta:
        model = PostNode
        fields = ['content']

forum/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotFound
from django.shortcuts import redirect, render, reverse

from .models import PostNode, PostNodeForm, Topic, TopicForm

def index(request, ordering="recent"):
    if (ordering == "popular"):
        topics = Topic.objects.all().order_by("-reply_count")
    elif (ordering == "recent"):
        topics = Topic.objects.all().order_by("-recent_update")
    else:
        return HttpResponseNotFound()
    return render(request, "forum/index.html", {'topics' : topics})

def view(request, id):
    topic = Topic.objects.filter(pk=id).first()
    if (topic == None):
        # error(request, "Matkul tidak ditemukan!")
        return redirect(reverse("forum:index"))
    else:
        return render(request, "forum/view.html", {'topic' : topic})

@login_required
def post(request):
    if (request.method == "POST"):
        topicform = TopicForm(request.POST or None)
        postnodeform = PostNodeForm(request.POST or None)
        if (topicform.is_valid() and postnodeform.is_valid()):
            topic = topicform.save(commit=False)
            postnode = postnodeform.save(commit=False)
            postnode.hidden = False
            postnode.user = request.user
            postnode.save()
            topic.head = postnode
            topic.author = request.user
            topic.save()
            # success(request, "Matkul telah ditambahkan!")
            return redirect(reverse('forum:index'))
        else:
            return render(request, 'forum/post.html', {'topicform' : topicform, 'postnodeform' : postnodeform})
    else:
        topicform = TopicForm()
        postnodeform = PostNodeForm()
    return render(request, 'forum/post.html', {'topicform' : topicform, 'postnodeform' : postnodeform})

@login_required
def reply(request, id):
    postnodedest = PostNode.objects.filter(pk=id).first()
    if (postnodedest == None):
        # error(request, "Matkul tidak ditemukan!")
        return redirect(reverse("forum:index"))
    temp = postnodedest
    if (request.method == "POST"):
        postnodeform = PostNodeForm(request.POST or None)
        if (postnodeform.is_valid()):
            postnode = postnodeform.save(commit=False)
            postnode.post = postnodedest
            postnode.author = request.user
            postnode.hidden = False
            postnode.save()
            # success(bla blabal)
            return redirect(reverse("forum:view", args=[postnode.update_topic().pk]))
        else:
            return render(request, "forum/reply.html", {"postnodeform" : postnodeform, "postnodedest" : postnodedest})
    else:
        postnodeform = PostNodeForm()
        return render(request, "forum/reply.html", {"postnodeform" : postnodeform, "postnodedest" : postnodedest})

templates/forum/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Forum{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" /> 
{% endblock %}
{% block content %}
<style>
.row {
    margin: 10px 0px 10px 0px;
}

p {
    vertical-align: middle;
}
</style>
<div class="container" style="max-width: 1000px; margin: auto; margin-top: 100px; margin-bottom: 100px;">
    <h1>Forum</h1>
    {% if user.is_authenticated %}
    Anda masuk sebagai {{ user.username }} <a href="{% url 'account:logout' %}">logout</a>
    {% else %}
    Silakan login atau daftar untuk post topik dan komentar
    {% endif %}
    <div class="row d-flex justify-content-between">
        <div class="btn-group" role="group" aria-label="Basic example">
            <a href="{% url 'forum:sortPost' 'recent' %}" class="btn btn-primary">Terbaru</a>
            <a href="{% url 'forum:sortPost' 'popular' %}" class="btn btn-primary">Populer</a>
        </div>
        {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'forum:post' %}">Post Topik</a>
        {% else %}
        <div role="group" aria-label="Basic example">
            <a class="btn btn-primary" href="{% url 'account:login' %}">Login</a>
            <a class="btn btn-primary" href="{% url 'account:signup' %}">Daftar</a>
        </div>
        {% endif %}
    </div>
    <ul class="list-group">
        {% for topic in topics %}
        <li class="list-group-item">
            <div class="d-flex justify-content-between">
                <div class="col-3">
                    <a href="{% url 'forum:view' topic.pk %}">{{ topic.title }}</a>
                    <div>Oleh: {% if topic.author %}{{ topic.author }}{% else %}Anonim{% endif %}</div>
                </div>
                <div class="col-2">
                    Balasan: {{ topic.reply_count }}
                </div>
                <div class="col-4">
                    Balasan terakhir: {{ topic.get_recent_datetime }}
                </div>
            </div>
        </li>
        {% endfor%}
    </ul>
</div>
{% endblock %}

templates/forum/post.html
{% extends "base.html" %}
{% load static %}
{% block title %}Forum | Post Topic{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" /> 
{% endblock %}
{% block content %}
{% load bootstrap4 %}
<div class="container" style="max-width: 1000px; margin: auto; margin-top: 100px; margin-bottom: 100px;">
    <h1>Post Topic</h1>
    <p>Post sebagai {{ user.username }} <a href="{% url 'account:logout' %}">logout</a></p>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form topicform %}
        {{ postnodeform.media }}
        {{ postnodeform.as_p }}
        <input class="btn btn-primary" type="submit" value="Post">
        <a class="btn btn-primary" href="{% url 'forum:index' %}">Kembali</a>
    </form>
</div>
{% endblock %}

templates/forum/posttemplate.html
{% if postnode.hidden %}
Post ini telah dihapus
{% else %}
<div id="postcontent">
    <b>{% if postnode.author %}{{ postnode.author }}{% else %}Anonim{% endif %}</b> - {{ postnode.get_creation_datetime }}
    <div>{{ postnode.content|safe }}</div>
</div>
{% endif %}
<a href="{% url 'forum:reply' postnode.pk %}">Balas</a>
{% if postnode.has_replies %}
    <ul id="reply">
        {% for childnode in postnode.postnode_set.all %}
            <li id="reply">{% include "forum/posttemplate.html" with postnode=childnode %}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/forum/reply.html
{% extends "base.html" %}
{% load static %}
{% block title %}Forum | Balas{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" /> 
{% endblock %}
{% block content %}
{% load bootstrap4 %}
<div class="container" style="max-width: 1000px; margin: auto; margin-top: 100px;">
    <h1>Balas</h1>
    <div class="card">
        <div class="card-body">
            <p class="card-text">
                <b>{% if postnodedest.author %}{{ postnodedest.author }}{% else %}Anonim{% endif %}</b> - {{ postnodedest.get_creation_datetime }} <br>
                {{ postnodedest.content|safe }}
            </p>
        </div>
    </div>
    <br>
    <div>Balas sebagai {{ user.username }} <a href="{% url 'account:logout' %}">logout</a></div>
    <form method="POST" style="margin-top: 20px;">
        {% csrf_token %}
        {{ postnodeform.media }}
        {{ postnodeform.as_p }}
        <input class="btn btn-primary" type="submit" value="Balas">
    </form>
</div>
{% endblock %}

templates/forum/view.html
{% extends "base.html" %}
{% load static %}
{% block title %}Forum | {{ topic.title }}{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'style.css' %}" /> 
{% endblock %}
{% block content %}

<style>
#postbox li{
    list-style: none;
    margin: 10px 0px 10px 0px;
    padding-left: 10px;
}

#postbox {
    padding-inline-start: 10px;
}

#post ul{
    border-left: 1px solid black;
    padding-inline-start: 1%;
}
#postcontent ul{
    padding-inline-start: 40px;
    border-left: none;
}

#postcontent li{
    padding-left: 0px;
    margin: 0px;
    list-style: disc;
}

@media (max-width: 1000px) {
    #postbox {
        padding-inline-start: 0px;
    }

    #post ul{
        border-left: 0.5px solid black;
        padding-inline-start: 0.5%;
    }

}
</style>

<div class="container" style="max-width: 1000px; margin: auto; margin-top: 100px; margin-bottom: 100px;">
    <h1>{{ topic.title }}</h1>
    <p>{{ topic.time_creation }} <a href="{% url 'forum:index' %}">Kembali</a></p>
    <p>Pembuat : {% if topic.author %}{{ topic.author }}{% else %}Anonim{% endif %}</p>
    <ul id="postbox">
        <li id="post">
            {% include "forum/posttemplate.html" with postnode=topic.head %}
        </li>
    </ul>
    <a href="{% url 'forum:index' %}" class="btn btn-primary" style="margin-top: 5px">Kembali</a>
</div>
{% endblock %}